name: chess_discord_bot
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
 chesscom_dart:
   git: https://github.com/V3ntus/chesscom_dart.git
 nyxx:
 nyxx_interactions:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
